<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Bib_Hacienda">
      <HintPath>lib/Bib_Hacienda.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
